server:
  port: 8085
  servlet:
    context-path: /memory

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info
