server:
  port: 18085
  servlet:
    context-path: /memory


spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: dev
logging:
  level:
    root: info
